### ISSUE TITLE
"Crystal Controller/Monitoring/Swift Cluster" page statusCode 404

### ISSUE THREAD

**Issue by xietiangui** [Crystal-SDS/dashboard#1]
After I installed the Crystal dashboard，The "Crystal Controller/Monitoring/Swift Cluster" page  statusCode is 404. Do I need some configuration to make this page display properly?
![](http://ww1.sinaimg.cn/large/76b1fa43gy1fpmkogku6qj227y13e42i.jpg)

**Comment by gerardparis** [comment]
You have to create a Kibana dashboard and then assign the id of the dashboard's short URL to the following setting in `/etc/openstack-dashboard/local_settings.py`, e.g.:
`CRYSTAL_MONITORING_DASHBOARD = "2ebe2fe8c..........4730c04"`

**Comment by xietiangui** [comment]
Thanks,I understand
